### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by OxInsky** [amdegroot/ssd.pytorch#149]
```
Namespace(basenet='vgg16_reducedfc.pth', batch_size=32, cuda=True, dataset='VOC', dataset_root='/raid/qj/exp_library/data/VOCdevkit/', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', start_iter=0, visdom=False, weight_decay=0.0005)
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train()
  File "train.py", line 178, in train
    out = net(images)
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 59, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/qj/tensorflow/pytorch/ssd.pytorch/ssd.py", line 77, in forward
    s = self.L2Norm(x)
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/raid/qj/tensorflow/pytorch/ssd.pytorch/layers/modules/l2norm.py", line 23, in forward
    x = torch.div(x,norm)
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/autograd/variable.py", line 315, in div
    return Div()(self, other)
  File "/home/qj/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/autograd/_functions/basic_ops.py", line 57, in forward
    return a.div(b)
RuntimeError: sizes do not match at /py/conda-bld/pytorch_1493679085273/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:344
```
In my training for Pascal VOC,I got the trouble up! I think there is some trouble in tensor but i cannot solve it! May you help me？ Then can you check the file of COCO-Trainval35k.json,zip ,which is broken from Amazon Cloud and cannot be unzipped,without unzip,the function cannot read the file.Thanks and wish your reply!

**Comment by OxInsky** [comment]
sorry to bother you!the matter i have solved!Remind as follow:
1.the torch version ,as I conda install the lastest version 0.1.12.when run the train.py with a matter that the function sum(x,keepdim=True) keepdim can not be recognized. so i changed the function into sum(x),but which cause the current error.so i mistake changed the torch version into 0.3.x.Sure changed the function to sum(x, keepdim=True).so there is a suggest that please follow the tools versions information as follow the git!thanks a lot!

**Comment by RyanCV** [comment]
@OxInsky I run python train.py with torch version 0.3.1 and python 3.5.2, but got the following errors, could u tell how to solve? Thx.
```
python3.5/site-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
THCudaCheck FAIL file=/pytorch/torch/lib/THC/THCGeneral.c line=844 error=59 : device-side assert triggered
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: device-side assert triggered
Aborted
```

**Comment by OxInsky** [comment]
@RyanCV I am sorry to answer you later. I don't think this is a code error. Just see the reason of the mistake  can not realize the specific mistake which causes. May you show the full mistake. There is a related discussion on stackoverflow:[https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-59-device-side-assert-triggered-at-opt-conda-conda-bld-pytorch-1503970438496-work-torch-lib-thc-generic-thcstorage-c-32/9669/8](url).Hope it works.
