### ISSUE TITLE
Training Error： ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by whao24** [amdegroot/ssd.pytorch#163]
Loading base network...
Initializing weights...
Loading the dataset...
Training SSD on: VOC0712
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=16, cuda=True, dataset='VOC', dataset_root='/home/whao/data/VOCdevkit/', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', start_iter=0, visdom=True, weight_decay=0.0005)
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/whao/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/whao/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/whao/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/whao/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/whao/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/whao/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa30126ff28>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

**Comment by HandsomeCao** [comment]
I met the same error, Can you tell me how to solve it.

**Comment by hoho131086** [comment]
I met the same error too.
@whao24 Can you share how you solve the problem?

**Comment by liuchang8am** [comment]
Solution: Start visdom server before training.
e.g. under sdd.pytorch
1. python -m visdom.server
2. python train.py (+ your args)
NOTE:
You may need to update several functions which are related to viz, i.e., add viz as an argument.
func: create_vis_plot()
func: update_vis_plot()
