### ISSUE TITLE
Issue running training

### ISSUE THREAD

**Issue by yuliiasergeeva** [amdegroot/ssd.pytorch#177]
Hello, when I run `python train.py` I get this:

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from data import *
  File "C:\Users\Yuliia\Install\SSD Multibox\ssd.pytorch\data\__init__.py", line 1, in <module>
    from .voc0712 import VOCDetection, VOCAnnotationTransform, VOC_CLASSES, VOC_ROOT
  File "C:\Users\Yuliia\Install\SSD Multibox\ssd.pytorch\data\voc0712.py", line 11, in <module>
    import torch
  File "C:\Users\Yuliia\Anaconda3\envs\tensorflow\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

What may cause this error and what's the fix? Thanks!

**Comment by IvanXieZS** [comment]
Hello, i meet the same problem. May i know the solution of the problem?
