### ISSUE TITLE
 test.py RuntimeError

### ISSUE THREAD

**Issue by 643683608** [amdegroot/ssd.pytorch#180]
Hello, I'm new to pytorch and I'm getting these errors when I run the test.py file:

Traceback (most recent call last):
  File "/home/sjt/virtualenv/pytorch_03/lib/python3.5/site-packages/torch/nn/modules/module.py", line 514, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:101

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 153, in <module>
    test_qr()
  File "test.py", line 136, in test_qr
    net.load_state_dict(torch.load(args.trained_model))
  File "/home/sjt/virtualenv/pytorch_03/lib/python3.5/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named conf.0.weight, whose dimensions in the model are torch.Size([12, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([8, 512, 3, 3]).

**Comment by liangxi627** [comment]
Hello, I met the same problem with you, have you solved it?

**Comment by zacario-li** [comment]
@643683608 have you fixed it now? I meet the similar problem.

**Comment by zacario-li** [comment]
@liangxi627 @643683608 I've found something, in test.py: test_voc() function, the author modified the num_classes + 1, I removed "+1", that works for me. So you should try to remove "+1" to check it.
