### ISSUE TITLE
ValueError when using python eval.py

### ISSUE THREAD

**Issue by tomorrow00** [amdegroot/ssd.pytorch#184]
Traceback (most recent call last):
  File "eval.py", line 438, in <module>
    thresh=args.confidence_threshold)
  File "eval.py", line 385, in test_net
    detections = net(x).data
  File "/home/wcc/miniconda2/envs/env_ws3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wcc/project_pytorch/ssd.pytorch-master/ssd.py", line 103, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "/home/wcc/project_pytorch/ssd.pytorch-master/layers/functions/detection.py", line 55, in forward
    ids, count = nms(boxes, scores, self.nms_thresh, self.top_k)
ValueError: not enough values to unpack (expected 2, got 0)

I use the model of 'ssd300_mAP_77.43_v2.pth'. Don't know what's wrong with this

**Comment by FawadArshad** [comment]
did u fix it?... i am having similar problem.. please help

**Comment by FawadArshad** [comment]
found it change scores.dims to scores.size(0)
https://github.com/amdegroot/ssd.pytorch/issues/154
