### ISSUE TITLE
trying to train on coco and receive this error:  from None json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by isalirezag** [amdegroot/ssd.pytorch#199]
```
loading annotations into memory...
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    train()
  File "train.py", line 82, in train
    MEANS))
  File "/home/alireza/ssd/A/data/coco.py", line 96, in __init__
    INSTANCES_SET.format(image_set)))
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/home/alireza/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/alireza/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/alireza/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/alireza/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by isalirezag** [comment]
After hitting my head to the wall for half a day, i notice this error is because there is something wrong with the provided json file. i change it withe train2014.json and it is gone. @amdegroot @ellisbrown  please update that file, it has something wrong with it

**Comment by DavideHe** [comment]
had you found the  detail erro of the json file? i generate the json file by myself.it's ok all the time ,but the last data i got was generated by the same way and get the same erro message "json.decoder.JSONDecodeError: Expecting value".i try to use the COCO("*.json") on my computer ,it's ok.but it's wrong when i use on the other computer.And i check the wrong positinon"line 64078900 column 7",there is noting different from with others.
