### ISSUE TITLE
COCO download script is broken

### ISSUE THREAD

**Issue by lemairecarl** [amdegroot/ssd.pytorch#205]
In the resulting folder, 

* `annotations/instances_trainval35k.json.zip` is corrupted (also why does the script downloads this but doesn't unzip it?)
* `coco_labels.txt` is missing (it can be found in `ssd.pytorch/data`)

There are no errors in the console output.

**Comment by seongkyun** [comment]
You can download that file on here.
https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip

**Comment by rebeen** [comment]
I think we can only train this model on coco but we can not test and evaluate, am I correctly understood 
Thank you

**Comment by elcolie** [comment]
@seongkyun 
I have followed your answer on my MBP2022. I got this error.
OSX 13.4.1 (c) (22F770820d)
Python 3.11.3
My packages [pip freeze.txt](https://github.com/amdegroot/ssd.pytorch/files/12474616/freeze.txt)

```bash
/Users/sarit/data/coco
loading annotations into memory...
Traceback (most recent call last):
  File "/Users/sarit/study/ssd.pytorch/train.py", line 256, in <module>
    train()
  File "/Users/sarit/study/ssd.pytorch/train.py", line 81, in train
    dataset = COCODetection(root=args.dataset_root,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/study/ssd.pytorch/data/coco.py", line 91, in __init__
    self.coco = COCO(osp.join(root, ANNOTATIONS,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/pycocotools/coco.py", line 82, in __init__
    dataset = json.load(f)
              ^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 69: invalid continuation byte

```

**Comment by elcolie** [comment]
> You can download that file on here. https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip After download, just change file's name correctly(instances_trainval35k.json) and copy that to correct directory(annotations/).
> 
> Then, you can train with MS COCO dataset.

You forgot to mention `extract` and rename it 👎

**Comment by floopypoppy** [comment]
> You can download that file on here. https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip After download, just change file's name correctly(instances_trainval35k.json) and copy that to correct directory(annotations/).
> 
> Then, you can train with MS COCO dataset.

Sorry but this link can't be found now. Can you please update it? Thanks!
