### ISSUE TITLE
AssertionError: Must define a window to update? why?

### ISSUE THREAD

**Issue by 237014845** [amdegroot/ssd.pytorch#234]
iter 2360 || Loss: 9.8369 || timer: 0.5007 sec.
iter 2370 || Loss: 9.9223 || timer: 0.4940 sec.
iter 2380 || Loss: 11.2484 || timer: 0.4787 sec.
iter 2390 || Loss: 10.6926 || timer: 0.4976 sec.
iter 2400 || Loss: 9.6664 || timer: 0.4990 sec.
iter 2410 || Loss: 10.5185 || timer: 0.5092 sec.
iter 2420 || Loss: 12.2446 || timer: 0.5129 sec.
iter 2430 || Loss: 12.2896 || timer: 0.4818 sec.
iter 2440 || Loss: 10.2730 || timer: 0.4859 sec.
iter 2450 || Loss: 10.4930 || timer: 0.5135 sec.
iter 2460 || Loss: 9.9998 || timer: 0.5068 sec.
iter 2470 || Loss: 11.2983 || timer: 0.5139 sec.
iter 2480 || Loss: 10.9896 || timer: 0.4783 sec.
iter 2490 || Loss: 9.8864 || timer: 0.5100 sec.
iter 2500 || Loss: 10.8051 || timer: 0.4982 sec.
iter 2510 || Loss: 10.4417 || timer: 0.4783 sec.
iter 2520 || Loss: 10.2917 || timer: 0.4758 sec.
iter 2530 || Loss: 10.9877 || timer: 0.4810 sec.
iter 2540 || Loss: 10.6649 || timer: 0.4757 sec.
iter 2550 || Loss: 10.9075 || timer: 0.4899 sec.
iter 2560 || Loss: 11.8318 || Traceback (most recent call last):
  File "train.py", line 266, in <module>
    train()
  File "train.py", line 159, in train
    'append', epoch_size)
  File "train.py", line 261, in update_vis_plot
    update=True
  File "/home/hs/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 288, in wrapped_f
    return f(*args, **kwargs)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 1207, in line
    update=update, name=name)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 288, in wrapped_f
    return f(*args, **kwargs)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 1010, in scatter
    assert win is not None, 'Must define a window to update'
AssertionError: Must define a window to update

**Comment by 237014845** [comment]
train on COCO dataset

**Comment by ankitksharma** [comment]
I'm getting the error on COCO dataset also. Any solution?

**Comment by 237014845** [comment]
> I'm getting the error on COCO dataset also. Any solution?

line 163 update_vis_plot(epoch, loc_loss, conf_loss, iter_plot, epoch_plot, 'append', epoch_size)

**Comment by d-li14** [comment]
@237014845 hi, you solved the problem by modifying this line: `update_vis_plot(epoch, loc_loss, conf_loss, iter_plot, epoch_plot, 'append', epoch_size)`? In my opinion, the `update_vis_plot` function keeps updating parameter `win1`, i.e. `iter_plot` instead of the expected `epoch_plot`.
And I think through just moving the line `epoch += 1` before `update_vis_plot`, this problem can be solved.

**Comment by chanajianyu** [comment]
anyone solve the problem?

**Comment by salt-fisher** [comment]
@chanajianyu I have faced the same problem, and adjust the code as your point. It works, thx

**Comment by chensonglu** [comment]
@d-li14 According to your fix, it works, thx.

**Comment by BerryLJ** [comment]
iter 730 || Loss: 6.8846 || timer: 0.4548 sec.
iter 740 || Loss: 6.6700 || timer: 0.4608 sec.
iter 750 || Loss: 6.8756 || timer: 0.4498 sec.
iter 760 || Loss: 6.4595 || Traceback (most recent call last):
  File "E:/ownstudy/ssd.pytorch-master/train.py", line 272, in <module>
    train()
  File "E:/ownstudy/ssd.pytorch-master/train.py", line 164, in train
    update_vis_plot(epoch, loc_loss, conf_loss, epoch_plot, None ,'append', epoch_size)
  File "E:/ownstudy/ssd.pytorch-master/train.py", line 267, in update_vis_plot
    update=update_type
  File "C:\Users\Berry\Anaconda3\envs\pytorch\lib\site-packages\visdom\__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\Berry\Anaconda3\envs\pytorch\lib\site-packages\visdom\__init__.py", line 1367, in line
    update=update, name=name)
  File "C:\Users\Berry\Anaconda3\envs\pytorch\lib\site-packages\visdom\__init__.py", line 335, in wrapped_f
    return f(*args, **kwargs)
  File "C:\Users\Berry\Anaconda3\envs\pytorch\lib\site-packages\visdom\__init__.py", line 1144, in scatter
    assert win is not None, 'Must define a window to update'
AssertionError: Must define a window to update

Process finished with exit code 1

Hello, does anyone know the reason? Thank you！

**Comment by SalahAdDin** [comment]
i'm getting the same error with **COCO** set.

**Comment by SalahAdDin** [comment]
@d-li14 
https://github.com/d-li14/ssd.pytorch/commit/36fc354a0aed372d1f835efa7ad5684c5ee13daf It is working for me, at least until now.
What's about making a PR?

**Comment by Monster-Zhang** [comment]
the num_class in config.py should +1  and in ssd.py are not

**Comment by ghost** [comment]
> @237014845 hi, you solved the problem by modifying this line: `update_vis_plot(epoch, loc_loss, conf_loss, iter_plot, epoch_plot, 'append', epoch_size)`? In my opinion, the `update_vis_plot` function keeps updating parameter `win1`, i.e. `iter_plot` instead of the expected `epoch_plot`.
> And I think through just moving the line `epoch += 1` before `update_vis_plot`, this problem can be solved.

It works,
```
if args.visdom and iteration != 0 and (iteration % epoch_size == 0):
    epoch += 1
    update_vis_plot(epoch, loc_loss, conf_loss, epoch_plot, None, 'append', epoch_size)
```
gooood!!
