### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Brozhao** [amdegroot/ssd.pytorch#242]
AttributeError: Traceback (most recent call last):
  File "/home/zt/anaconda3/envs/pytorch-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zt/anaconda3/envs/pytorch-3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zt/pytorch/ssd.pytorch/data/voc0712.py", line 117, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/home/zt/pytorch/ssd.pytorch/data/voc0712.py", line 129, in pull_item
    height, width, channels = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

Whether the images is reading  in？Please help me！Thanks////

**Comment by Brozhao** [comment]
I think I have fix it out.Thanks all the same......

**Comment by lakshmanbathina** [comment]
how you fixed bro?

**Comment by zz10001** [comment]
> I think I have fix it out.Thanks all the same......

can you share how to fix it？much obligated！
