### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by yeyuxiaoxiang01** [amdegroot/ssd.pytorch#257]
when I run train.py with pycharm. It said 'RuntimeError: CUDA error: out of memory'. I want to know what happened and what should I do. 
My video card is GTX960m with 4G memory.
Thank you very much.

**Comment by yeyuxiaoxiang01** [comment]
the news is this:
`/home/magicalzh/code/pytorch-ssd/ssd.pytorch/train.py:171: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  targets = [Variable(ann.cuda(), volatile=True) for ann in targets]
Traceback (most recent call last):
  File "/home/magicalzh/code/pytorch-ssd/ssd.pytorch/train.py", line 257, in <module>
    train()
  File "/home/magicalzh/code/pytorch-ssd/ssd.pytorch/train.py", line 177, in train
    out = net(images)
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/magicalzh/code/pytorch-ssd/ssd.pytorch/ssd.py", line 75, in forward
    x = self.vgg[k](x)
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 142, in forward
    self.return_indices)
  File "/home/magicalzh/app/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 396, in max_pool2d
    ret = torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA error: out of memory`

**Comment by LZP4GitHub** [comment]
Do you solved it? I meet the same question with you.

**Comment by LZP4GitHub** [comment]
Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train()
  File "train.py", line 196, in train
    out = net(images)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_a                                                pply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_a                                                pply
    raise output
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/Code/ssd.pytorch/ssd.py", line 79, in forward
    x = self.vgg[k](x)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by LZP4GitHub** [comment]
`Traceback (most recent call last):
  File "train.py", line 287, in <module>
    train()
  File "train.py", line 196, in train
    out = net(images)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_a                                                pply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_a                                                pply
    raise output
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/Code/ssd.pytorch/ssd.py", line 79, in forward
    x = self.vgg[k](x)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
`

**Comment by yeyuxiaoxiang01** [comment]
> `Traceback (most recent call last): File "train.py", line 287, in <module> train() File "train.py", line 196, in train out = net(images) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__ result = self.forward(*input, **kwargs) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward outputs = self.parallel_apply(replicas, inputs, kwargs) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_a pply return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)]) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_a pply raise output File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker output = module(*input, **kwargs) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__ result = self.forward(*input, **kwargs) File "/home/lzp/Code/ssd.pytorch/ssd.py", line 79, in forward x = self.vgg[k](x) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__ result = self.forward(*input, **kwargs) File "/home/lzp/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward self.padding, self.dilation, self.groups) RuntimeError: CUDA error: out of memory `



> Do you solved it? I meet the same question with you.

No! I think maybe batch_size is too large. And I resize batch_size to 16. But it also can't run. And my notebook's memory is 16G. Do you have some methods? Very sad!

**Comment by wendyltan** [comment]
I have to resize it to 6 until I can run it on my GTX 860

**Comment by BITTER799** [comment]
I make the batch_size to 4 then I solve the problem.

**Comment by cotyyang** [comment]
I also make the batch_size to 4 then I solve the problem.
