### ISSUE TITLE
when i run train.py, an error occur in multibox_loss.py as follow: RuntimeError Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by xiaozhao00** [amdegroot/ssd.pytorch#278]
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    train()
  File "train.py", line 41, in train
    train_model()
  File "/home/juzhaoxue/project/ssds.pytorch/lib/ssds_train.py", line 607, in train_model
    s.train_model()
  File "/home/juzhaoxue/project/ssds.pytorch/lib/ssds_train.py", line 237, in train_model
    self.train_epoch(self.model, self.train_loader, self.optimizer, self.criterion, self.write    r, epoch, self.use_gpu)
  File "/home/juzhaoxue/project/ssds.pytorch/lib/ssds_train.py", line 296, in train_epoch
    loss_l, loss_c = criterion(out, targets)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in     __call__
    result = self.forward(*input, **kwargs)
  File "/home/juzhaoxue/project/ssds.pytorch/lib/layers/modules/multibox_loss.py", line 124, i    n forward
    loss_c = F.cross_entropy(conf_p, targets_weighted, size_average=False)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cro    ss_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction    )
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 975, in log_    softmax
    return input.log_softmax(dim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

anyone can help?
thx

**Comment by xiaozhao00** [comment]
solved

**Comment by zhuyu-06** [comment]
I now have the same problem, can you tell me how to solve it?
Thank you very much!
