### ISSUE TITLE
KeyError: 'unexpected key "0.weight" in state_dict'

### ISSUE THREAD

**Issue by shiwenhao** [amdegroot/ssd.pytorch#28]
when doing 'python test.py',the output is the following:
Traceback (most recent call last):
File "test.py", line 73, in <module>
net.load_state_dict(torch.load(args.trained_model))
File "/home/qz/lzjqsdd/APP/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict .format(name))
Do you have any idea why this could be happening?Thanks

**Comment by amdegroot** [comment]
Hi sorry for the delayed response. This should be fixed with the latest version.  Try again and let me know if the issue still exists.  Closing for now.

**Comment by amdegroot** [comment]
Hi sorry for the delayed response. This should be fixed with the latest version.  Try again and let me know if the issue still exists.  Closing for now.

**Comment by alexiskattan** [comment]
I get a the same thing when I do `net.load_weights('./weights/vgg16_reducedfc.pth')` for the Jupyter notebook.

```
Loading weights into state dict...
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    net.load_weights('./weights/vgg16_reducedfc.pth')
  File "/home/alexis/coding/ssd.pytorch/ssd.py", line 116, in load_weights
    self.load_state_dict(torch.load(base_file, map_location=lambda storage, loc: storage))
  File "/home/alexis/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "0.weight" in state_dict'
```
