### ISSUE TITLE
self.variance = cfg['variance'], TypeError: 'module' object is not subscriptable

### ISSUE THREAD

**Issue by qishuaihui** [amdegroot/ssd.pytorch#282]
when I train the model, the 'train.py' tell me this error, How can I solve it?

**Comment by jelly0o0** [comment]
``from data.config import coco, voc``

Add this at the top of python files.

**Comment by will-qzq** [comment]
> `from data.config import coco, voc`
> 
> 将其添加到python文件的顶部。

添加后仍然报错，请问该如何解决

**Comment by pjg205** [comment]
HI it seems like my current situation. I use my custom data and modify config.py. Did this(from data.config import custom_voc as cfg) worked? When I run eval.py after adding this on the top of python files, the error shows up like this. What should I do to solve it? Please, let me know the way to solve it

Traceback (most recent call last):
  File "eval.py", line 437, in <module>
    test_net(args.save_folder, net, args.cuda, dataset,
  File "eval.py", line 386, in test_net
    detections = net(x).data
  File "/opt/conda/envs/prac/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/SSD.Pytorch/ssd.py", line 105, in forward
    output = self.detect.apply(17, 0, 200, 0.01, 0.45,
  File "/data/SSD.Pytorch/layers/functions/detection.py", line 111, in forward
    self.variance = cfg['variance']
KeyError: 'variance'
