### ISSUE TITLE
The version of pytorch is？？？thansks~~ I see both 0.4.1 and 1.0.0 have the same promblem

### ISSUE THREAD

**Issue by QiuPaul** [amdegroot/ssd.pytorch#312]
It's about the dataset 

iter 90 || Loss: 16.6367 || timer: 0.2197 sec.
iter 100 || Loss: 11.2141 || timer: 0.2131 sec.
iter 110 || Loss: 14.3660 || timer: 0.2441 sec.
iter 120 || Loss: 94.8293 || timer: 0.1988 sec.
iter 130 || Loss: nan || timer: 0.2064 sec.
iter 140 || Loss: nan || timer: 0.2058 sec.
Traceback (most recent call last):
  File "/media/paul/新加卷/Project/ssd.pytorch-master/train.py", line 258, in <module>
    train()
  File "/media/paul/新加卷/Project/ssd.pytorch-master/train.py", line 166, in train
    images, targets = next(batch_iterator)
  File "/home/paul/anaconda2/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 627, in __next__
    raise StopIteration
iter 150 || Loss: nan || StopIteration﻿

**Comment by QiuPaul** [comment]
problem solved by using terminate instead of using pycharm.

**Comment by krxat** [comment]
@QiuPaul How did you solve the 'Loss: nan'? I also got the same output and the saved model didn't do any good. And how did you use terminate? 
 Please help. Thanks

**Comment by WalkingWoo** [comment]
@QiuPaul @cypherix Please try to decrease lr

**Comment by QiuPaul** [comment]
@cypherix , I solved the nan by swapping the line 97 and 98，final result is below:

  loss_c = loss_c.view(num, -1)
  loss_c[pos] = 0

**Comment by espectre** [comment]
@QiuPaul https://github.com/amdegroot/ssd.pytorch/issues/214#issuecomment-409851395
