### ISSUE TITLE
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other'

### ISSUE THREAD

**Issue by dx1122** [amdegroot/ssd.pytorch#323]
Traceback (most recent call last):
  File "train.py", line 261, in <module>
    train()
  File "train.py", line 184, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/sypark/anaconda3/envs/syDeep/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sypark/ssd.pytorch-master/layers/modules/multibox_loss.py", line 74, in forward
    loc_t, conf_t, idx)
  File "/home/sypark/ssd.pytorch-master/layers/box_utils.py", line 91, in match
    point_form(priors)
  File "/home/sypark/ssd.pytorch-master/layers/box_utils.py", line 62, in jaccard
    inter = intersect(box_a, box_b)
  File "/home/sypark/ssd.pytorch-master/layers/box_utils.py", line 43, in intersect
    box_b[:, 2:].unsqueeze(0).expand(A, B, 2))
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other'

what is that?? help me.

**Comment by JappaB** [comment]
`if torch.cuda.is_available():
torch.set_default_tensor_type('torch.cuda.FloatTensor')`

This should help, put it in the beginning of your script
