### ISSUE TITLE
Expected object of scalar type Float but got scalar type Byte for sequence elment 1 insequence argument at position #1 'tensors'

### ISSUE THREAD

**Issue by GYC1996** [amdegroot/ssd.pytorch#325]
I found a problem:

File "train.py", line 175, in train
    images, targets = next(batch_iterator)
  File "/home/yuechaoguo/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/yuechaoguo/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/yuechaoguo/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/disk1/yuechaoguo/ssd.pytorch/data/__init__.py", line 30, in detection_collate
    return torch.stack(imgs, 0), targets
RuntimeError: Expected object of scalar type Float but got scalar type Byte for sequence elment 1 insequence argument at position #1 'tensors'

**Comment by lsding** [comment]
same error
