### ISSUE TITLE
This is because of what

### ISSUE THREAD

**Issue by tom666tom666** [amdegroot/ssd.pytorch#327]
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train()
  File "train.py", line 198, in train
    loss_l, loss_c = criterion(out, targets)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qiuyj/SSD/layers/modules/multibox_loss.py", line 101, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
RuntimeError: The shape of the mask [1, 8732] at index 0 does not match the shape of the indexed tensor [8732, 1] at index 0

use VOC dataset
`

**Comment by qigtang** [comment]
having the same problem here.

**Comment by wjourney** [comment]
I have the same problem. Have you solved it?

**Comment by qigtang** [comment]
I modified the code this way. Seems working.

@@ -95,8 +95,8 @@ class MultiBoxLoss(nn.Module):
         loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))

         # Hard Negative Mining
-        loss_c[pos] = 0  # filter out pos boxes for now
         loss_c = loss_c.view(num, -1)
+        loss_c[pos] = 0  # filter out pos boxes for now
         _, loss_idx = loss_c.sort(1, descending=True)
         _, idx_rank = loss_idx.sort(1)
         num_pos = pos.long().sum(1, keepdim=True)

**Comment by qigtang** [comment]
I changed the code the following way, seems working fine for me.

```diff
@@ -95,8 +95,8 @@ class MultiBoxLoss(nn.Module):
         loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))

         # Hard Negative Mining
-        loss_c[pos] = 0  # filter out pos boxes for now
         loss_c = loss_c.view(num, -1)
+        loss_c[pos] = 0  # filter out pos boxes for now
         _, loss_idx = loss_c.sort(1, descending=True)
         _, idx_rank = loss_idx.sort(1)
         num_pos = pos.long().sum(1, keepdim=True)
```

**Comment by yuanshengyu** [comment]
> 
> 
> I changed the code the following way, seems working fine for me.
> 
> ```diff
> @@ -95,8 +95,8 @@ class MultiBoxLoss(nn.Module):
>          loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))
> 
>          # Hard Negative Mining
> -        loss_c[pos] = 0  # filter out pos boxes for now
>          loss_c = loss_c.view(num, -1)
> +        loss_c[pos] = 0  # filter out pos boxes for now
>          _, loss_idx = loss_c.sort(1, descending=True)
>          _, idx_rank = loss_idx.sort(1)
>          num_pos = pos.long().sum(1, keepdim=True)
> ```

it works fine for me too. But I meet another problem, Loss keeps NAN

**Comment by J0hannB** [comment]
> it works fine for me too. But I meet another problem, Loss keeps NAN

Same problem here. 

Maybe we're doing something else wrong that causes the error in the first place? Moving the `loss_c[pos] = 0` line might be fixing a symptom, not the original issue.

**Comment by J0hannB** [comment]
I was able to fix my nan issue. 

My solution: https://github.com/amdegroot/ssd.pytorch/issues/173#issuecomment-565566649
