### ISSUE TITLE
when run train.py on  my dataset ,meet some problems.

### ISSUE THREAD

**Issue by optionalis** [amdegroot/ssd.pytorch#330]
I don't know what to do.
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train()
  File "train.py", line 170, in train
    images, targets = next(batch_iterator)
  File "/home/acer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/acer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/acer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/acer/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/acer/ssd_pytorch/data/voc0712.py", line 111, in __getitem__\n    im, gt, h, w = self.pull_item(index)\n  File "/home/acer/ssd_pytorch/data/voc0712.py", line 126, in pull_item\n    target = self.target_transform(target, width, height)\n  File "/home/acer/ssd_pytorch/data/voc0712.py", line 68, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'crane\'\n'

**Comment by isyanan1024** [comment]
I have the same problem. Why is this?

**Comment by sxyxf66** [comment]
@optionalis @isyanan1024  I have the similar problem when I run the train.py code on my dataset. Do you fix it?

**Comment by optionalis** [comment]
@sxyxf66
you can use "[]".like this
![image](https://user-images.githubusercontent.com/50021489/57455838-aa5afe00-729e-11e9-9e30-0b007a9b408e.png)

**Comment by kongcong** [comment]
> @sxyxf66
> you can use "[]".like this
> ![image](https://user-images.githubusercontent.com/50021489/57455838-aa5afe00-729e-11e9-9e30-0b007a9b408e.png)

I changed this, but it dose't work

**Comment by HanningLin** [comment]
Have you changed the VOC_CLASSES before trainning. There is no "crane" in that class.

**Comment by optionalis** [comment]
yes，I use my date。

**Comment by sxyxf66** [comment]
> @sxyxf66
> you can use "[]".like this

You're great. It works. Thank you very much.

Do you have problems when you use your trained models in the demo.py?

RuntimeError: Error(s) in loading state_dict for SSD:
size mismatch for conf.0.weight: copying a param with shape torch.Size([8, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
size mismatch for conf.0.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
size mismatch for conf.1.weight: copying a param with shape torch.Size([12, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 1024, 3, 3]).
size mismatch for conf.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
size mismatch for conf.2.weight: copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 512, 3, 3]).
size mismatch for conf.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
size mismatch for conf.3.weight: copying a param with shape torch.Size([12, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 256, 3, 3]).
size mismatch for conf.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
size mismatch for conf.4.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
size mismatch for conf.4.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
size mismatch for conf.5.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
size mismatch for conf.5.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current mode is torch.Size([84]).

It similar the weight of the trained model is wrong


I

**Comment by sxyxf66** [comment]
> @sxyxf66
> you can use "[]".like this
> 
> You're great. It works. Thank you very much.
> Do you have problems when you use your trained models in the demo.py?
> RuntimeError: Error(s) in loading state_dict for SSD:
> size mismatch for conf.0.weight: copying a param with shape torch.Size([8, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
> size mismatch for conf.0.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
> size mismatch for conf.1.weight: copying a param with shape torch.Size([12, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 1024, 3, 3]).
> size mismatch for conf.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.2.weight: copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 512, 3, 3]).
> size mismatch for conf.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.3.weight: copying a param with shape torch.Size([12, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 256, 3, 3]).
> size mismatch for conf.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.4.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
> size mismatch for conf.4.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
> size mismatch for conf.5.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
> size mismatch for conf.5.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current mode is torch.Size([84]).
> It similar the weight of the trained model is wrong
> I
I fix it.

**Comment by Ai-is-light** [comment]
@sxyxf66 
 same problem , when test or run demo, how do you solve it

**Comment by Damon2019** [comment]
@sxyxf66 hi ,could you tell me how to fix it?thanks

**Comment by Damon2019** [comment]
@sxyxf66 i meet the same problem

**Comment by optionalis** [comment]
@Damon2019
>>x
x
>>>(x,)
(x,)
if there is only one element, you should use the second method。add ,

**Comment by Y132om** [comment]
> @sxyxf66
> you can use "[]".like this
> ![image](https://user-images.githubusercontent.com/50021489/57455838-aa5afe00-729e-11e9-9e30-0b007a9b408e.png)

How should I add multiple categories?

**Comment by liujiale1234** [comment]
VOC_CLASSES = [('Pointer')]
but is doesnt work

**Comment by AnhPC03** [comment]
> > @sxyxf66
> > you can use "[]".like this
> > ![image](https://user-images.githubusercontent.com/50021489/57455838-aa5afe00-729e-11e9-9e30-0b007a9b408e.png)
> 
> How should I add multiple categories?

@Y132om You can add multiple categories as: 
```VOC_CLASSES = [('label_1', 'label_2', 'label_3')]```

**Comment by sxyxf66** [comment]
delete the ()发自我的华为手机-------- 原始邮件 --------发件人： AnhPC03 <notifications@github.com>日期： 2020年7月24日周五 下午4:54收件人： "amdegroot/ssd.pytorch" <ssd.pytorch@noreply.github.com>抄送： sxyxf66 <13269273379@163.com>, Mention <mention@noreply.github.com>主    题： Re: [amdegroot/ssd.pytorch] when run train.py on  my dataset ,meet some problems. (#330)


@sxyxf66
you can use "[]".like this


How should I add multiple categories?

You can add multiple categories as:
VOC_CLASSES = [('label_1', 'label_2', 'label_3')]
