### ISSUE TITLE
KeyError When running python eval.py.

### ISSUE THREAD

**Issue by LiuShuaiyr** [amdegroot/ssd.pytorch#333]
Traceback (most recent call last):
  File "eval.py", line 427, in <module>
    net = build_ssd('test', 300, num_classes)            # initialize SSD
  File "/home/ls/liushuai/code/ssd.pytorch-master/ssd.py", line 209, in build_ssd
    return SSD(phase, size, base_, extras_, head_, num_classes)
  File "/home/ls/liushuai/code/ssd.pytorch-master/ssd.py", line 33, in __init__
    self.priorbox = PriorBox(self.cfg)
  File "/home/ls/liushuai/code/ssd.pytorch-master/layers/functions/prior_box.py", line 15, in __init__
    self.num_priors = len(cfg['aspect_ratios'])
KeyError: 'aspect_ratios'

**Comment by LiuShuaiyr** [comment]
It has been solved.

**Comment by sxyxf66** [comment]
hello，when i run the eval.py, it like this
_jb_pytest_runner.py: error: unrecognized arguments: F:/pychqarmtestdemo/ssd.pytorch-master/eval.py
do you know how to solve it?
