### ISSUE TITLE
Error in training(Error in training)

### ISSUE THREAD

**Issue by xlm998** [amdegroot/ssd.pytorch#337]
Error in training
iter 900 || Loss: 6.6272 || timer: 0.1010 sec.
iter 910 || Loss: 7.0335 || timer: 0.1023 sec.
iter 920 || Loss: 6.6000 || timer: 0.1001 sec.
iter 930 || Loss: 6.7137 || timer: 0.1013 sec.
iter 940 || Loss: 6.9450 || timer: 0.1027 sec.
iter 950 || Loss: 6.5815 || timer: 0.1038 sec.
iter 960 || Loss: 6.8804 || timer: 0.1021 sec.
iter 970 || Loss: 6.6749 || timer: 0.1279 sec.
iter 980 || Loss: 6.4802 || timer: 0.1018 sec.
iter 990 || Loss: 6.1978 || timer: 0.1184 sec.
iter 1000 || Loss: 6.7934 || timer: 0.1019 sec.
iter 1010 || Loss: 6.5664 || timer: 0.1028 sec.
iter 1020 || Loss: 6.6167 || timer: 0.0977 sec.
iter 1030 || Loss: 6.3809 || Traceback (most recent call last):
  File "train.py", line 261, in <module>
    train()
  File "train.py", line 166, in train
    images, targets = next(batch_iterator)
  File "/home/xlm/anaconda3/envs/M2Det/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 627, in __next__
    raise StopIteration
StopIteration
when i change batch-size and learning-rate,the iteration were change,but allways
 <1200

**Comment by Thome** [comment]
Duplicate of #214 
The fix suggested by seongkyun worked for me

**Comment by xlm998** [comment]
when i change  
    images, targets = next(batch_iterator)
    with
    try:
           images,targets = next(batch_iterator)
        except StopIteration:
            bath_interator = iter(data_loader)
            images,targets = next(batch_iterator)
but this error was still occured.
As follows:
iter 990 || Loss: 6.8619 || timer: 0.0993 sec.
iter 1000 || Loss: 7.1491 || timer: 0.1010 sec.
iter 1010 || Loss: 6.9546 || timer: 0.0996 sec.
iter 1020 || Loss: 7.1629 || timer: 0.1168 sec.
iter 1030 || Loss: 7.2130 || Traceback (most recent call last):
  File "train.py", line 168, in train
    images,targets = next(batch_iterator)
  File "/home/xlm/anaconda3/envs/M2Det/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 627, in __next__
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 261, in <module>
    train()
  File "train.py", line 171, in train
    images,targets = next(batch_iterator)
  File "/home/xlm/anaconda3/envs/M2Det/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 627, in __next__
    raise StopIteration
StopIteration

**Comment by yyx1107** [comment]
https://github.com/amdegroot/ssd.pytorch/issues/312#issuecomment-476028789
