### ISSUE TITLE
my weights trained by my own datasets is wrong

### ISSUE THREAD

**Issue by leijuzi** [amdegroot/ssd.pytorch#342]
my weights trained by my own datasets is wrong
![image](https://user-images.githubusercontent.com/42333539/57276466-4edd1480-70d4-11e9-8ff2-ffcd2e05b17f.png)
i didnt change the net, i dont know why my weights size is 103733 but 102686

**Comment by sxyxf66** [comment]
when I use the trained model with my dataset in the demo.py, it has the problem:
Traceback (most recent call last):
  File "F:/pychqarmtestdemo/ssd.pytorch-master/demo/demo.py", line 20, in <module>
    net.load_weights('../weights/ssd300_fengfeng_400.pth')
  File "F:\pychqarmtestdemo\ssd.pytorch-master\ssd.py", line 120, in load_weights
    map_location=lambda storage, loc: storage))
  File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SSD:
	size mismatch for conf.0.weight: copying a param with shape torch.Size([8, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
	size mismatch for conf.0.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for conf.1.weight: copying a param with shape torch.Size([12, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 1024, 3, 3]).
	size mismatch for conf.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.2.weight: copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 512, 3, 3]).
	size mismatch for conf.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.3.weight: copying a param with shape torch.Size([12, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 256, 3, 3]).
	size mismatch for conf.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.4.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
	size mismatch for conf.4.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for conf.5.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
	size mismatch for conf.5.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).

Process finished with exit code 1

Is the error same with yours?

**Comment by SafiyaHashmi12** [comment]
I am getting the same error too.:(

**Comment by LinRui9531** [comment]
> when I use the trained model with my dataset in the demo.py, it has the problem:
> Traceback (most recent call last):
> File "F:/pychqarmtestdemo/ssd.pytorch-master/demo/demo.py", line 20, in 
> net.load_weights('../weights/ssd300_fengfeng_400.pth')
> File "F:\pychqarmtestdemo\ssd.pytorch-master\ssd.py", line 120, in load_weights
> map_location=lambda storage, loc: storage))
> File "C:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
> self.class.name, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SSD:
> size mismatch for conf.0.weight: copying a param with shape torch.Size([8, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
> size mismatch for conf.0.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
> size mismatch for conf.1.weight: copying a param with shape torch.Size([12, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 1024, 3, 3]).
> size mismatch for conf.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.2.weight: copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 512, 3, 3]).
> size mismatch for conf.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.3.weight: copying a param with shape torch.Size([12, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 256, 3, 3]).
> size mismatch for conf.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
> size mismatch for conf.4.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
> size mismatch for conf.4.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
> size mismatch for conf.5.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
> size mismatch for conf.5.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
> Process finished with exit code 1
> Is the error same with yours?

I am also getting the same error

**Comment by QW-Is-Here** [comment]
similar issues  here

**Comment by Ouwzhong** [comment]
That's because before you train your network, there's a file that hasn't been modified.
This file is called `config. py` and is in the `data` folder.
You should modify the` num_class` in line 15 or 31 based on the dataset format you use and the number of classes in your custom dataset.

**Comment by SalahAdDin** [comment]
@Ouwzhong well, `coco_labels.txt` file contains 80 or 81 classes, i put both numbers but it still does not work.

**Comment by engmubarak48** [comment]
> @Ouwzhong well, `coco_labels.txt` file contains 80 or 81 classes, I put both numbers but it still does not work.

@Ouwzhong  said before you train. So, before training, you have to modify that file.

**Comment by Ouwzhong** [comment]
> @Ouwzhong well, `coco_labels.txt` file contains 80 or 81 classes, i put both numbers but it still does not work.

@SalahAdDin 

In the model, there are two locations related to the number of classes, `config.py` and `ssd.py`, respectively.
One location involves the name of classes, in `voc0712.py` or `coco.py`.
In `ssd.py`, you should change
 `self.cfg = (coco, voc)[num_classes == 21]` 
to  
`self.cfg = (coco, voc)[num_classes == 81]` (if you have 80 classes).

If the parameters of your network are set correctly, the trained model should be no problem, and the wrong part I think should be evaluation.
Please make sure that the network parts in `ssd.py` and `eval.py` are **not** modified. If you can't guarantee, you can download the source code of these two files again. 
After I reloaded the source code, the problem disappeared. 
(However, the custom dataset format I use is VOC. I'm not sure about the specific parameter settings for the coco dataset.)

**Comment by SalahAdDin** [comment]
@Ouwzhong after modifying that lines I must to train the network again, isn't it?

**Comment by Ouwzhong** [comment]
@SalahAdDin

Yes.
Or maybe you should have a test train that only iterates 100 or less times.
You can modify `train.py`  in line 194
 `if iteration != 0 and iteration % 5000 == 0`
to 
`if iteration != 0 and iteration % 100 == 0`, 
so that you can save a check point file only after 100 iterations. (It will save your time, and if you use it can run `eval.py`, you can change it to whatever times you want! )

**Comment by SalahAdDin** [comment]
@Ouwzhong Well, i did it, and i still got the same problem.

You can see it here in my [pr](https://github.com/punrong/ssd.pytorch/pull/1/files).

I ran up the code with this modifications, and i still got that problem, mismatch problem.

**Comment by Damon2019** [comment]
@SafiyaHashmi12 me too,can you solved?

**Comment by liujiale1234** [comment]
I have trained,but still have this question

**Comment by CindyZhengPersonal** [comment]
I had the same error but fixed it according to this. https://github.com/amdegroot/ssd.pytorch/issues/346
