### ISSUE TITLE
line 83, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError:

### ISSUE THREAD

**Issue by sxyxf66** [amdegroot/ssd.pytorch#343]

**Comment by sxyxf66** [comment]
when i use my dataset, i have the problem 
KeyError: 'Traceback (most recent call last):\n  File "C:\\Program Files\\Anaconda3\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "C:\\Program Files\\Anaconda3\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "F:\\pychqarmtestdemo\\ssd.pytorch-master\\data\\voc0712.py", line 126, in __getitem__\n    im, gt, h, w = self.pull_item(index)\n  File "F:\\pychqarmtestdemo\\ssd.pytorch-master\\data\\voc0712.py", line 141, in pull_item\n    target = self.target_transform(target, width, height)\n  File "F:\\pychqarmtestdemo\\ssd.pytorch-master\\data\\voc0712.py", line 83, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'feng\'\n


feng is the lable name

**Comment by LeiGan0215** [comment]
you can use VOC_CLASSES = [(
'feng')] instead

**Comment by liujiale1234** [comment]
I have the same question,do you solve it? and  how?

**Comment by liujiale1234** [comment]
> 您可以改用VOC_CLASSES = [（
> 'feng'）]
it doesnt work

**Comment by zeroorhero** [comment]
> > 您可以改用VOC_CLASSES = [（
> > 'feng'）]
> > it doesnt work

您好！我遇到了同样的问题，您解决了吗？可以探讨一下！

**Comment by sxyxf66** [comment]
没有()发自我的华为手机-------- 原始邮件 --------发件人： zeroorhero <notifications@github.com>日期： 2020年2月7日周五 早上8:49收件人： "amdegroot/ssd.pytorch" <ssd.pytorch@noreply.github.com>抄送： sxyxf66 <13269273379@163.com>, Author <author@noreply.github.com>主    题： Re: [amdegroot/ssd.pytorch] line 83, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: (#343)



您可以改用VOC_CLASSES = [（

'feng'）]

it doesnt work





您好！我遇到了同样的问题，您解决了吗？可以探讨一下！

**Comment by calvin886** [comment]
> 没有()发自我的华为手机-------- 原始邮件 --------发件人： zeroorhero <notifications@github.com>日期： 2020年2月7日周五 早上8:49收件人： "amdegroot/ssd.pytorch" <ssd.pytorch@noreply.github.com>抄送： sxyxf66 <13269273379@163.com>, Author <author@noreply.github.com>主 题： Re: [amdegroot/ssd.pytorch] line 83, in __call__\n label_idx = self.class_to_ind[name]\nKeyError: (#343) 您可以改用VOC_CLASSES = [（ 'feng'）] it doesnt work 您好！我遇到了同样的问题，您解决了吗？可以探讨一下！ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

作者您好，遇到了一样的问题，请问你们解决了吗之前

**Comment by AntoineGerardeaux** [comment]
Hello, i'm facing the same issue and i dont know how to do i tried many things =(

**Comment by cnr0724** [comment]
Hello, anyone solved this issue? LeiGan's comment didn't work for me.

**Comment by AntoineGerardeaux** [comment]
> 
> 
> Hello, anyone solved this issue? LeiGan's comment didn't work for me.

Hello, you may try this when you define your classes : YOUR_CLASSES = [（'Label_1') , ('Label_2') , ('Label_3') ]

**Comment by MehmetZahidGenc** [comment]
Hello, you also must also upgrade coco_classes.py like voc_classes.py
