### ISSUE TITLE
one problem with my own dataset

### ISSUE THREAD

**Issue by sxyxf66** [amdegroot/ssd.pytorch#345]
when i use my dataset, i have the problem
KeyError: 'Traceback (most recent call last):\n File "C:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "C:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 138, in \n samples = collate_fn([dataset[i] for i in batch_indices])\n File "F:\pychqarmtestdemo\ssd.pytorch-master\data\voc0712.py", line 126, in getitem\n im, gt, h, w = self.pull_item(index)\n File "F:\pychqarmtestdemo\ssd.pytorch-master\data\voc0712.py", line 141, in pull_item\n target = self.target_transform(target, width, height)\n File "F:\pychqarmtestdemo\ssd.pytorch-master\data\voc0712.py", line 83, in call\n label_idx = self.class_to_ind[name]\nKeyError: 'feng'\n
feng is the lable name

Do you know how to fix it?

**Comment by LeiGan0215** [comment]
you can use VOC_CLASSES = [(
    'feng')] instead

**Comment by Y132om** [comment]
> you can use VOC_CLASSES = [(
> 'feng')] instead

How to add multiple categories？

**Comment by cenchaojun** [comment]
> > you can use VOC_CLASSES = [(
> > 'feng')] instead
> 
> How to add multiple categories？

may be VOC_CLASSES = [('feng','yu')]

**Comment by sxyxf66** [comment]
对，在后面加标签名就行发自我的华为手机-------- 原始邮件 --------发件人： 岑朝君 <notifications@github.com>日期： 2020年3月24日周二 下午4:37收件人： "amdegroot/ssd.pytorch" <ssd.pytorch@noreply.github.com>抄送： sxyxf66 <13269273379@163.com>, Author <author@noreply.github.com>主    题： Re: [amdegroot/ssd.pytorch] one problem with my own dataset (#345)





you can use VOC_CLASSES = [(

'feng')] instead



How to add multiple categories？



may be VOC_CLASSES = [('feng','yu')]
