### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by tangtaogo** [amdegroot/ssd.pytorch#353]
Traceback (most recent call last):
  File "train.py", line 257, in <module>
    train()
  File "train.py", line 177, in train
    out = net(images)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 119, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 130, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 87, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/cuda/comm.py", line 142, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: out of memory (allocate at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCCachingAllocator.cpp:510)
frame #0: THCStorage_resize + 0x1ea (0x7f0894bd676a in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #1: THCTensor_resizeNd + 0x34f (0x7f0894be4e9f in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: THCudaTensor_newWithStorage + 0xfe (0x7f0894bed18e in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::CUDAFloatType::th_tensor(at::ArrayRef<long>) const + 0x67 (0x7f0894b0f707 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #4: at::native::tensor(at::Type const&, at::ArrayRef<long>) + 0x4a (0x7f08a9e27d0a in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #5: at::Type::tensor(at::ArrayRef<long>) const + 0x1d (0x7f08aa01694d in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: torch::autograd::VariableType::tensor(at::ArrayRef<long>) const + 0x54 (0x7f08abd40fc4 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #7: at::Type::copy(at::Tensor const&, bool) const + 0x233 (0x7f08aa035973 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #8: torch::cuda::scatter(at::Tensor const&, at::ArrayRef<long>, at::optional<std::vector<long, std::allocator<long> > > const&, long, at::optional<std::vector<CUDAStreamInternals*, std::allocator<CUDAStreamInternals*> > > const&) + 0x1509 (0x7f08ac1b2e89 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0xba586b (0x7f08ac1b886b in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x353609 (0x7f08ab966609 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #21: THPFunction_apply(_object*, _object*) + 0x412 (0x7f08abcf36e2 in /data/tangtao/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)

**Comment by tangtaogo** [comment]
And i set batch_size=2, it didn't work,too. So sad, what's wrong with this, who can help me

**Comment by jaychou790118** [comment]
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

add os.environ['CUDA_VISIBLE_DEVICES'] = '1' or 
 os.environ['CUDA_VISIBLE_DEVICES'] = '0' below import os
it will work.

**Comment by lbda1** [comment]
> import os
> os.environ['CUDA_VISIBLE_DEVICES'] = '1'
> 
> add os.environ['CUDA_VISIBLE_DEVICES'] = '1' or
> os.environ['CUDA_VISIBLE_DEVICES'] = '0' below import os
> it will work.

It's work
