### ISSUE TITLE
Problem during training

### ISSUE THREAD

**Issue by lzh19961031** [amdegroot/ssd.pytorch#360]
When I want to train my own data, I meet a problem 
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    train()
  File "train.py", line 183, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/pku/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pku/毕设/ssd.pytorch-master/layers/modules/multibox_loss.py", line 74, in forward
    loc_t, conf_t, idx)
  File "/home/pku/毕设/ssd.pytorch-master/layers/box_utils.py", line 93, in match
    point_form(priors)
  File "/home/pku/毕设/ssd.pytorch-master/layers/box_utils.py", line 64, in jaccard
    inter = intersect(box_a, box_b)
  File "/home/pku/毕设/ssd.pytorch-master/layers/box_utils.py", line 45, in intersect
    box_b[:, 2:].unsqueeze(0).expand(A, B, 2))
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'other'

**Comment by yyx1107** [comment]
不太清楚，最好用中文路径

**Comment by Y132om** [comment]
我也遇到了同样的问题，请问你是怎么就解决的。这个貌似和路径没关系

**Comment by lhn217** [comment]
同问
