### ISSUE TITLE
Why the shape does not match

### ISSUE THREAD

**Issue by chrisyxue** [amdegroot/ssd.pytorch#401]
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train()
  File "train.py", line 178, in train
    loss_l, loss_c = criterion(out, targets)
  File "/data6/home/xuezhiyu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data6/home/xuezhiyu/TeamWork/ssd.pytorch-master/layers/modules/multibox_loss.py", line 97, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
IndexError: The shape of the mask [32, 8732] at index 0 does not match the shape of the indexed tensor [279424, 1] at index 0

**Comment by yyx1107** [comment]
issue里有过这个问题，我当时好像也遇到过，你看看issue


 
---Original---

**Comment by uzair789** [comment]
Has this been resolved? I have the same problem..Can you help ? thank you!

**Comment by uzair789** [comment]
Resolved here--  some error in code #518
