### ISSUE TITLE
train.py errors. Please help me

### ISSUE THREAD

**Issue by haesungg** [amdegroot/ssd.pytorch#414]
File "C:/Users/해성/PycharmProjects/Pytorch/train.py", line 255, in <module>
    train()
  File "C:/Users/해성/PycharmProjects/Pytorch/train.py", line 165, in train
    images, targets = next(batch_iterator)
  File "C:\ProgramData\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\ProgramData\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\ProgramData\Anaconda3\envs\PyTorch\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\해성\PycharmProjects\Pytorch\data\voc0712.py", line 115, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "C:\Users\해성\PycharmProjects\Pytorch\data\voc0712.py", line 127, in pull_item
    height, width, channels = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

How can i fix this?
I'm solving this problem during two days

**Comment by Y132om** [comment]
Modified voc0712.py file: VOC_CLASSES =[ ('tvmonitor'),('person')]

**Comment by haesungg** [comment]
> Modified voc0712.py file: VOC_CLASSES =[ ('tvmonitor'),('person')]

thanks for your reply, but it doesn't work.. :(

**Comment by yanww2010** [comment]
You can check your dataset ,maybe some format is .JPG while others are .jpg. If so ,you can correct them to .jpg and try again
