### ISSUE TITLE
KeyError: 'Traceback (most recent call last):\n  File "E:\\anaconda\\anaconda\\envs\\pytorch\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "E:\\anaconda\\anaconda\\envs\\pytorch\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 111, in __getitem__\n    im, gt, h, w = self.pull_item(index)\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 126, in pull_item\n    target = self.target_transform(target, width, height)\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 68, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'pointer_instrument\'\n'

### ISSUE THREAD

**Issue by liujiale1234** [amdegroot/ssd.pytorch#423]
KeyError: 'Traceback (most recent call last):\n  File "E:\\anaconda\\anaconda\\envs\\pytorch\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "E:\\anaconda\\anaconda\\envs\\pytorch\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 111, in __getitem__\n    im, gt, h, w = self.pull_item(index)\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 126, in pull_item\n    target = self.target_transform(target, width, height)\n  File "F:\\ssd.pytorch-master\\data\\voc0712.py", line 68, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'pointer_instrument\'\n'
how can I solve it？
I only have 40 data

**Comment by neverstoplearn** [comment]
I have meet the same error have you solve it? thanks.

**Comment by calvin886** [comment]
same error. Have you guys solve it?

**Comment by jayphone17** [comment]
same issue, have you solved it ? thanks a lot

**Comment by jayphone17** [comment]
Loading base network...
Initializing weights...
Loading the dataset...
Training SSD on: SMOKE
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=8, cuda=True, dataset='VOC', dataset_root='E:/ssd.pytorch/data/VOCdevkit/VOCsmoke/', gamma=0.1, lr=1e-05, momentum=0.9, num_workers=4, resume=None, s4, resume=None, save_folder='E:/ssd.pytorch/weights/', start_iter=0, visdom=False, weight_decay=0.0005)
Traceback (most recent call last):
  File ".\train.py", line 254, in <module>
    train()
  File ".\train.py", line 156, in train
    images, targets = next(batch_iterator)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "D:\Anaconda3\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ssd.pytorch\data\smoke.py", line 114, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "E:\ssd.pytorch\data\smoke.py", line 129, in pull_item
    target = self.target_transform(target, width, height)
  File "E:\ssd.pytorch\data\smoke.py", line 68, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'smoke'

**Comment by jayphone17** [comment]
and the  line 156 is :
        try:
            images, targets = next(batch_iterator)
        except StopIteration:
            batch_iterator = iter(data_loader)
            images, targets = next(batch_iterator)
