### ISSUE TITLE
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by wudi00** [amdegroot/ssd.pytorch#445]
I met this error in training.
`Original Traceback (most recent call last):
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/disk/wudi/SSD/ssd/data/datasets/voc.py", line 50, in __getitem__
    boxes, labels = self.target_transform(boxes, labels)
  File "/media/disk/wudi/SSD/ssd/data/transforms/target_transform.py", line 21, in __call__
    self.corner_form_priors, self.iou_threshold)
  File "/media/disk/wudi/SSD/ssd/utils/box_utils.py", line 89, in assign_priors
    best_target_per_prior, best_target_per_prior_index = ious.max(1)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
`
Why does this occur? Thanks.

**Comment by xhpk** [comment]
hello do you solve this proble? how?

**Comment by xhpk** [comment]
> I met this error in training.
> `Original Traceback (most recent call last): File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/disk/wudi/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/disk/wudi/SSD/ssd/data/datasets/voc.py", line 50, in __getitem__ boxes, labels = self.target_transform(boxes, labels) File "/media/disk/wudi/SSD/ssd/data/transforms/target_transform.py", line 21, in __call__ self.corner_form_priors, self.iou_threshold) File "/media/disk/wudi/SSD/ssd/utils/box_utils.py", line 89, in assign_priors best_target_per_prior, best_target_per_prior_index = ious.max(1) RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity `
> Why does this occur? Thanks.

hello do you solve this proble? how?
