### ISSUE TITLE
Index Error on Train on VOC2012

### ISSUE THREAD

**Issue by MNCTTY** [amdegroot/ssd.pytorch#451]
Hi! I downloaded VOC2012 dataset and ran a training with original train.py, but got an error

```
~/nefteprovod/ssd.pytorch$ python3 train.py 
/home/karina/nefteprovod/ssd.pytorch/ssd.py:34: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
Loading base network...
Initializing weights...
train.py:214: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(param)
Loading the dataset...
Training SSD on: VOC0712
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=32, cuda=True, dataset='VOC', dataset_root='/home/karina/nefteprovod/ssd.pytorch/data/VOCdevkit/', gamma=0.1, lr=0.001, momentum=0.9, num_workers=4, resume=None, save_folder='weights/', start_iter=0, visdom=False, weight_decay=0.0005)
train.py:169: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  targets = [Variable(ann.cuda(), volatile=True) for ann in targets]
/usr/local/lib/python3.5/dist-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train()
  File "train.py", line 178, in train
    loss_l, loss_c = criterion(out, targets)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karina/nefteprovod/ssd.pytorch/layers/modules/multibox_loss.py", line 97, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
IndexError: The shape of the mask [32, 8732] at index 0does not match the shape of the indexed tensor [279424, 1] at index 0
```

do you have any ideas what to do?

**Comment by WalkingWoo** [comment]
You can fix the bugs like this.
https://github.com/amdegroot/ssd.pytorch/issues/421#issuecomment-545861899

**Comment by MNCTTY** [comment]
thank you!
