### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by sujeet764** [amdegroot/ssd.pytorch#464]
/home/cya/git_clones/ssd.pytorch/ssd.py:34: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
/home/cya/git_clones/ssd.pytorch/layers/modules/l2norm.py:17: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.weight,self.gamma)
[INFO] starting threaded video stream...
Traceback (most recent call last):
  File "demo/live.py", line 82, in <module>
    cv2_demo(net.eval(), transform)
  File "demo/live.py", line 55, in cv2_demo
    frame = predict(frame)
  File "demo/live.py", line 25, in predict
    y = net(x)  # forward pass
  File "/home/cya/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cya/git_clones/ssd.pytorch/ssd.py", line 103, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "/home/cya/git_clones/ssd.pytorch/layers/functions/detection.py", line 54, in forward
    ids, count = nms(boxes, scores, self.nms_thresh, self.top_k)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by gjxgjxgjxgjx** [comment]
函数返回的值不够

**Comment by soongjian** [comment]
detection.py                
line 49
indtead "if scores.dim() == 0:"     with        "  if scores.size(0)==0:"
