### ISSUE TITLE
No such file or directory：VOCdevkit/VOC2007\\ImageSets\\Main\\test.txt

### ISSUE THREAD

**Issue by yahaha6** [amdegroot/ssd.pytorch#470]
There is not the file--“VOCdevkit/VOC2007\\ImageSets\\Main\\test.txt” in VOC2007 dataset  I downloaded. 
When I run eval.py,
Finished loading model!
Traceback (most recent call last):
  File "D:/Personal/My_Subject/SSD/ssd.pytorch-master/eval.py", line 469, in <module>
    VOCAnnotationTransform())
  File "D:\Personal\My_Subject\SSD\ssd.pytorch-master\data\voc0712.py", line 111, in __init__
    for line in open(osp.join(rootpath, 'ImageSets', 'Main', name + '.txt')):
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Personal\\My_Subject\\SSD\\ssd.pytorch-master\\data/VOCdevkit/VOC2007\\ImageSets\\Main\\test.txt'
There is not the file--“VOCdevkit/VOC2007\\ImageSets\\Main\\test.txt” in VOC2007 dataset  I downloaded. 
How can I get the file --"test.txt"?

**Comment by AtriSaxena** [comment]
Answered in Issue #471
