### ISSUE TITLE
No such file or directory: 'test.txt' when using eval.py

### ISSUE THREAD

**Issue by qWildManp** [amdegroot/ssd.pytorch#489]
Traceback (most recent call last):
  File "eval.py", line 438, in <module>
    thresh=args.confidence_threshold)
  File "eval.py", line 413, in test_net
    evaluate_detections(all_boxes, output_dir, dataset)
  File "eval.py", line 418, in evaluate_detections
    do_python_eval(output_dir)
  File "eval.py", line 175, in do_python_eval
    ovthresh=0.5, use_07_metric=use_07_metric)
  File "eval.py", line 262, in voc_eval
    with open(imagesetfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

**Comment by dikshaaswal** [comment]
Having same issue.

**Comment by AtriSaxena** [comment]
You need to download the VOC test data also. For doing the evaluation. You might have downloaded only training data.

**Comment by ziseyanhua1** [comment]
> Traceback (most recent call last):
> File "eval.py", line 438, in
> thresh=args.confidence_threshold)
> File "eval.py", line 413, in test_net
> evaluate_detections(all_boxes, output_dir, dataset)
> File "eval.py", line 418, in evaluate_detections
> do_python_eval(output_dir)
> File "eval.py", line 175, in do_python_eval
> ovthresh=0.5, use_07_metric=use_07_metric)
> File "eval.py", line 262, in voc_eval
> with open(imagesetfile, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

**Comment by ziseyanhua1** [comment]
Have you solved this problem? I have also encountered such a problem. Please ask me

**Comment by ronichester** [comment]
I had the same issue, but just solved it by fixing 2 lines in the code.
Here is the solution:
Fix the line which specifies imgsetpath as below:
`imgsetpath = os.path.join(args.voc_root, 'VOC2007', 'ImageSets', 'Main', '%s.txt') `

And later on inside the function do_python_eval fix the following line
```
# filename, annopath, imgsetpath.format(set_type), cls, cachedir,
           filename, annopath, imgsetpath % set_type, cls, cachedir,
```

It is simply a matter of notation;  os.path.join does not accept joing a path with brackets "{:s}.txt" as in the original implemenation. It would ignore all the path ~/VOC2007/ImageSets/Main/test.txt and would simply assume the path is :
currentpath/test.txt

Another solution which works but i think is less elegant, is just to find the file (test.txt) in the correct path, and copy it to the current path.
cheers
