### ISSUE TITLE
train.py:KeyError: 'van'

### ISSUE THREAD

**Issue by zhao-97** [amdegroot/ssd.pytorch#513]
This's my bug:
-----------------
iter 0 || Loss: 20.2327 || timer: 0.1706 sec.
iter 10 || Loss: 12.8549 || Traceback (most recent call last):
  File "train.py", line 259, in <module>
    train()
  File "train.py", line 165, in train
    images, targets = next(batch_iterator)
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/its/anaconda3/envs/torch13/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/its/ssd.pytorch/data/voc0712.py", line 118, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/home/its/ssd.pytorch/data/voc0712.py", line 133, in pull_item
    target = self.target_transform(target, width, height)
  File "/home/its/ssd.pytorch/data/voc0712.py", line 74, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'van'
------------------------
I think the question was caused by the capital letter.
my VOC_CLASSES is 'Car', 'Bus','Truck','Van','Minibus' , and I have changed<name = obj.find('name').text.lower().strip()> into          <name = obj.find('name').text.strip()> (voc0712.py)
where should I change?

**Comment by jayphone17** [comment]
same issue, have you solved it ? thanks a lot

**Comment by jayphone17** [comment]
Loading base network...
Initializing weights...
Loading the dataset...
Training SSD on: SMOKE
Using the specified args:
Namespace(basenet='vgg16_reducedfc.pth', batch_size=8, cuda=True, dataset='VOC', dataset_root='E:/ssd.pytorch/data/VOCdevkit/VOCsmoke/', gamma=0.1, lr=1e-05, momentum=0.9, num_workers=4, resume=None, s4, resume=None, save_folder='E:/ssd.pytorch/weights/', start_iter=0, visdom=False, weight_decay=0.0005)
Traceback (most recent call last):
File ".\train.py", line 254, in
train()
File ".\train.py", line 156, in train
images, targets = next(batch_iterator)
File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 363, in next
data = self._next_data()
File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
return self._process_data(data)
File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
data.reraise()
File "D:\Anaconda3\lib\site-packages\torch_utils.py", line 395, in reraise
raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\torch\utils\data_utils\worker.py", line 185, in _worker_loop
data = fetcher.fetch(index)
File "D:\Anaconda3\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "D:\Anaconda3\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "E:\ssd.pytorch\data\smoke.py", line 114, in getitem
im, gt, h, w = self.pull_item(index)
File "E:\ssd.pytorch\data\smoke.py", line 129, in pull_item
target = self.target_transform(target, width, height)
File "E:\ssd.pytorch\data\smoke.py", line 68, in call
label_idx = self.class_to_ind[name]
KeyError: 'smoke'

**Comment by jayphone17** [comment]
and the line 156 is :
try:
images, targets = next(batch_iterator)
except StopIteration:
batch_iterator = iter(data_loader)
images, targets = next(batch_iterator)
