### ISSUE TITLE
Only one object label

### ISSUE THREAD

**Issue by Blahblah-Z** [amdegroot/ssd.pytorch#543]
When I defined  VOC_CLASSES = {‘person’} {line 20} in voc0712.py，I got a KeyError. How can I set this class name correctly? If anybody has solved this problem, please share your experiece with me. Thank you very much. 

Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train()
  File "train.py", line 172, in train
    images, targets = next(batch_iterator)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/ssd.pytorch/data/voc0712.py", line 125, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/content/drive/MyDrive/ssd.pytorch/data/voc0712.py", line 140, in pull_item
    target = self.target_transform(target, width, height)
  File "/content/drive/MyDrive/ssd.pytorch/data/voc0712.py", line 76, in __call__
    label_idx = self.class_to_ind[name]
KeyError: 'person'

**Comment by gabrielpan147** [comment]
I met the same problem days ago. There is probably a typo in your training data label.
