### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'COCO_ROOT'

### ISSUE THREAD

**Issue by Zhezhefufu** [amdegroot/ssd.pytorch#544]
Hey guys! I got this issue:

Traceback (most recent call last):
  File "test.py", line 102, in <module>
    test_voc()
  File "test.py", line 92, in test_voc
    testset = COCODetection(args.COCO_ROOT, 'trainval35k', None, COCOAnnotationTransform)
AttributeError: 'Namespace' object has no attribute 'COCO_ROOT'

Could you plz give me some advices how to fix it

**Comment by Zhezhefufu** [comment]
FIX IT
