### ISSUE TITLE
eval my voc dataset ' __init__() missing 5 required positional arguments'

### ISSUE THREAD

**Issue by Carolyn0822** [amdegroot/ssd.pytorch#583]
D:\LeStoreDownload\anaconda3\envs\mytest\python.exe "D:/LeStoreDownload/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 52771 --file D:\Carolyn\INS_AI\ssd.pytorch\eval.py 
Connected to pydev debugger (build 222.4167.33)
Traceback (most recent call last):
  File "D:/LeStoreDownload/PyCharm Community Edition 2022.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\LeStoreDownload\PyCharm Community Edition 2022.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\Carolyn\INS_AI\ssd.pytorch\eval.py", line 430, in <module>
    net = build_ssd('test', 300, num_classes)            # initialize SSD
  File "D:\Carolyn\INS_AI\ssd.pytorch\ssd.py", line 218, in build_ssd
    return SSD(phase, size, base_, extras_, head_, num_classes)
  File "D:\Carolyn\INS_AI\ssd.pytorch\ssd.py", line 51, in __init__
    self.detect = Detect()
TypeError: __init__() missing 5 required positional arguments: 'num_classes', 'bkg_label', 'top_k', 'conf_thresh', and 'nms_thresh'

**Comment by lb1234564** [comment]
解决这个问题了吗？

**Comment by Xingjie-Han** [comment]
您好，请问这个问题解决了吗？

**Comment by Sunzuquan** [comment]
请问这个问题解决了吗

**Comment by Xingjie-Han** [comment]
您的来信已收到。

**Comment by wei3044** [comment]
请问这个问题有无大佬解决了

**Comment by Xingjie-Han** [comment]
您的来信已收到。
