### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by BattleOfDance** [amdegroot/ssd.pytorch#598]
when i use eval.py to evaluate my model. it reports this problem. How can i solve this problem?

**Comment by BattleOfDance** [comment]
this is the whole problem report
D:\PycharmProjects\ssd-master\ssd.py:34: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
Finished loading model!
Traceback (most recent call last):
  File "D:/PycharmProjects/ssd-master/eval.py", line 438, in <module>
    thresh=args.confidence_threshold)
  File "D:/PycharmProjects/ssd-master/eval.py", line 385, in test_net
    detections = net(x).data
  File "D:\Anaconda\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

Process finished with exit code 1

**Comment by BattleOfDance** [comment]
The problem was caused by adding     @staticmethod up the forward function in ssd.py classs ssd
![1713015532982](https://github.com/amdegroot/ssd.pytorch/assets/93129367/e60ce891-7e16-43fd-90c8-30e7b4eb3471)

**Comment by BattleOfDance** [comment]
Del this ,it will report 
![1713015585383](https://github.com/amdegroot/ssd.pytorch/assets/93129367/b1584af3-723c-4811-b382-1d4cfdda5b3f)

**Comment by BattleOfDance** [comment]
changing
![1713015896827](https://github.com/amdegroot/ssd.pytorch/assets/93129367/0138036f-dd47-4a2b-84cd-e93b0b873b5b)
to 
![1713015924696](https://github.com/amdegroot/ssd.pytorch/assets/93129367/d798d206-da1f-4b75-b6c1-128a29ef81b7)
it still report 
![1713015957181](https://github.com/amdegroot/ssd.pytorch/assets/93129367/6e79675f-8491-480c-99ab-1407eae51589)

**Comment by BattleOfDance** [comment]
according this blog， I resolved this problem finally
https://blog.csdn.net/XiaoGShou/article/details/125253471
