### ISSUE TITLE
Can't train

### ISSUE THREAD

**Issue by kunguz** [amdegroot/ssd.pytorch#60]
kaan@ALTAR:ssd.pytorch$ python3 train.py 
Loading base network...
Initializing weights...
Loading Dataset...
Training SSD on VOC0712
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train()
  File "train.py", line 170, in train
    images, targets = next(batch_iterator)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 40, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/kaan/ssd.pytorch/data/voc0712.py", line 117, in __getitem__
    im, gt, h, w = self.pull_item(index)
  File "/home/kaan/ssd.pytorch/data/voc0712.py", line 129, in pull_item
    height, width, channels = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by hdjang** [comment]
Hi. I got the same problem as you. 

Why did you close this issue? Did you solve?

If so, can you share your solution?

**Comment by LAWSSSS** [comment]
can you share your solution? I get the same problem with you. Thx.

**Comment by krxat** [comment]
@kunguz Did you solve it?
If yes, what was the problem and how did you solve it??

**Comment by zz10001** [comment]
> If yes, what was the problem and how did you solve it??

i have met the same trouble，did you deal with it？thank your watching！

**Comment by HanningLin** [comment]
Maybe there is no that file. Please check does the pic file exsist. I tried to train kitti. First I converted kitti to VOC format. Then I met this problem. It turned out that my picture is in png format. After I change those pictures to jpg format. The problem is solved. BTW, if this is your problem you can use this command to convert the picutres.`ls -1 *.png | xargs -n 1 bash -c 'convert "$0" "${0%.png}.jpg"'`
